name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write  # Allows the action to write text back to your README file

jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_TOTAL: true
          LANG_COUNT: 5
